#!/usr/bin/python3

import subprocess
import sys
import os
import copy
import shutil

CC="gcc"
LINKER="gcc"
CFLAGS="-O2 -c $INPUT -o $OUTPUT -std=gnu99 -Wall \
-fdiagnostics-color=always -I include/"
EXECUTABLE="mkfs.eosfs"
LDFLAGS="-o $OUTPUT -O2 $INPUT -lgcc"

EXT = {
    "c" : {
        "C" : CC,
        "F" : CFLAGS
    }
}

SOURCES=["mkfs.eosfs.c"
         ]

NOWARN = []

def build():
    print("=== \033[95mStarting build...\033[0m ===")
    OBJECTS = []
    for f in SOURCES:
        print("Compiling " + f)
        if not os.path.isfile(f):
            print("File " + f + " doesn't exists, exiting.")
            sys.exit(0)
        fname = f.split(".")
        tmpfname = copy.copy(fname)
        tmpfname[len(tmpfname)-1] = "o"
        fout = ".".join(tmpfname)

        fext = fname[len(fname)-1]
        if not fext in ["c", "s"]: continue
        if not fext in EXT:
            print("Unknown file extension " + fext + ", exiting.")
            sys.exit(0)
        cc = EXT[fext]["C"]
        flags = EXT[fext]["F"]
        if "$INPUT" in flags:
            flags = flags.replace("$INPUT", f)
        else:
            flags += " " + f
        if "$OUTPUT" in flags:
            flags = flags.replace("$OUTPUT", fout)
        else:
            flags += " " + fout
        if f in NOWARN:
            flags += " -w"
        subprocess.run(args=[cc]+flags.split(), check=True)
        OBJECTS.append(fout)
    print("=== \033[95mLinking...\033[0m ===")
    flags = LDFLAGS
    if "$INPUT" in flags:
        flags = flags.replace("$INPUT", " ".join(OBJECTS))
    else:
        flags += " " + " ".join(OBJECTS)
    if "$OUTPUT" in flags:
        flags = flags.replace("$OUTPUT", EXECUTABLE)
    else:
        flags += " " + EXECUTABLE
    subprocess.run(args=[CC]+flags.split(), check=True)
    print("Output: " + os.path.abspath(EXECUTABLE))

def clean():
    print("Cleaning...")
    for f in SOURCES:
        fname = f.split(".")
        fname[len(fname)-1] = "o"
        nfn = ".".join(fname)
        if os.path.isfile(nfn):
            os.remove(nfn)
    if os.path.isfile(EXECUTABLE):
        os.remove(EXECUTABLE)

if __name__ == "__main__":
    if len(sys.argv) > 1:
        if "clean" in sys.argv:
            clean()
        if "build" in sys.argv:
            build()
    else:
        build()